---
- name: install kubernetes (admin)
  become: yes
  apt:
    name:
      - kubelet={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
      - kubeadm={{ kubernetes_version }}
      - kubernetes-cni={{ kubernetes_cni_version }}
    state: present
  when: kubernetes_node_type == 'admin'

