---
- name: install kubernetes (master)
  become: yes
  apt:
    name:
      - kubelet={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
      - kubernetes-cni={{ kubernetes_cni_version }}
    state: present

