---
- name: install kubernetes (worker)
  become: yes
  apt:
    name:
      - kubelet={{ kubernetes_version }}
      - kubeadm={{ kubernetes_version }}
      - kubernetes-cni={{ kubernetes_cni_version }}
    state: present
